---
title: "Textbook Home Page"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: false
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

**Welcome to Math 221**

Use the menus along the top, or the links in the table below to navigate to the desired lesson. Links to the [Math 221 Statistics Toolbox](./Data/Math221StatisticsToolbox.xltx) and data files used in the book can also be found at the "Data" link on the far right of the header above.

<br/>

<div class="mboxfull">
<a href="javascript:showhide('Unit1')"><div class="mbox usermessage">Unit 1: Quantitative Data</div></a>

<div id="Unit1" style="display:none;">

<table class="tmain">
<tr>
<td><p>[Lesson 1: (On Campus) Course Intro & Probability](Lesson01_Campus.html) <a href="javascript:showhide('lesson01_Campus_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson01_Campus_Outcomes" style="display:none;">
By the end of this lesson, you should be able to:

- Understand and explain the course policies
- Access course resources (course outline, lesson schedule, preparation activities, reading quizzes, homework assignments, assessments, Zoom, etc.)
- Communicate with your instructor
- Obtain access to a spreadsheet program (Microsoft Excel)
- Discuss ways in which you will apply gospel principles to your work in this class
</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 1: (Online) Course Intro & Probability](Lesson01.html) <a href="javascript:showhide('lesson01_Online_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson01_Online_Outcomes" style="display:none;">
By the end of this lesson, you should be able to:

* Understand and explain the course policies
* Access course resources (course outline, lesson schedule, preparation activities, reading quizzes, homework assignments, assessments, Zoom, etc.)
* Communicate with your instructor
* Obtain access to a spreadsheet program (Microsoft Excel)
* Discuss ways in which you will apply gospel principles to your work in this class
* State and apply the three rules of probability.
</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 2: The Statistical Process & Design of Studies](Lesson02.html) <a href="javascript:showhide('lesson02_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson02_Outcomes" style="display:none;">
By the end of this lesson, you should be able to:

* State the five steps of the Statistical Process
* Distinguish between an observational study and an experiment.
* Distinguish between a population and a sample.
* Distinguish between a categorical and a quantitative variable.
* Distinguish and give an example of each of the following sampling schemes:
  + Simple random sampling
  + Systematic sampling
  + Cluster sampling
  + Stratified sampling
  + Convenience sampling
* Explain the significance of using a random sample.
</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 3: Describing Quantitative Data (Shape & Center)](Lesson03.html) <a href="javascript:showhide('lesson03_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson03_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

* Determine the shape of a distribution using a histogram.
* Interpret the mean, median, and mode for quantitative data.
* Apply the Excel functions AVERAGE, MEDIAN, and MODE when working with quantitative data in Excel.
* Determine the location of the mean relative to the median of left-skewed, right-skewed, or bell-shaped distributions visually using a histogram.
* Interpret a histogram.  
* Distinguish between a parameter and a statistic.
</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 4: Describing Quantitative Data (Spread)](Lesson04.html) <a href="javascript:showhide('lesson04_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson04_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

* Approximate the standard deviation of a distribution visually from a bell-shaped histogram.
* Calculate the standard deviation from quantitative data using Excel.
* Interpret the standard deviation for symmetric distributions. 
* Properly apply the Excel functions STDEV.S, PERCENTILE.INC, QUARTILE.INC, MIN, and MAX to quantitative data.
* Interpret the five-number summary for quantitative data.
* Create a box-plot from quantitative data using Excel. 
* Determine the five-number summary visually from a box plot. * Explain the relationship between probabilities, percentiles, and percentages.

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 5: Normal Distributions](Lesson05.html) <a href="javascript:showhide('lesson05_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson05_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

* State the properties of a normal density curve.
* Calculate the z-score of an individual observation, given the mean and standard deviation.
* Interpret a z-score.
* Calculate probability as area under a normal density curve.
* Calculate a percentile using the normal distribution.

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 6: Distribution of Sample Means & The Central Limit Theorem](Lesson06.html) <a href="javascript:showhide('lesson06_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson06_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

*  Explain how a sampling distribution is created.
*  Determine the mean, standard deviation and shape of a distribution of sample means.
*  State and apply the Central Limit Theorem and the Law of Large Numbers.

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 7: Calculating Probabilities involving the Sample Mean](Lesson07.html) <a href="javascript:showhide('lesson07_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson07_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

*  Calculate probabilities using a distribution of sample means.

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 8: Review for Exam 1](Lesson08.html) <a href="javascript:showhide('lesson08_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson08_Outcomes" style="display:none;">

Unit 1 Review. The expectation on the Unit 1 Exam is that you should be able to do the following:

- Distinguish between a categorical and a quantitative variable.
- Distinguish between an observational study and an experiment.
- Distinguish between a population and a sample.
- Distinguish between a parameter and a statistic.
- Distinguish and give an example of each of the following sampling schemes:

  + Simple random sampling
  + Systematic sampling
  + Cluster sampling
  + Stratified sampling
  + Convenience sampling

- Explain the significance of using a random sample.
- Determine the shape of a distribution using a histogram and/or boxplot.
- Determine the centers of a given histogram and/or boxplot. 
- Identify the mean, median and standard deviation in skewed or normal histograms.
- Calculate the mean, median and standard deviation from quantitative data.
- Calculate a percentile from a quantitative data set.
- Calculate a five-number summary from quantitative data with Excel, or by hand.
- Create a histogram and a boxplot from quantitative data. 
- State and apply the three axioms of probability.
- State the properties of a normal density curve.
- Calculate the z-score of an individual observation, given the mean and standard deviation.
- Interpret a z-score.
- Calculate probability as area under a normal density curve.
- Assess normality using a histogram.
- Explain how a sampling distribution is created.
- Determine the mean, standard deviation, and shape of a distribution of sample means.
- State and apply the Central Limit Theorem and the Law of Large numbers.
- Calculate probabilities using a distribution of sample means.
</div>
</p></td>
</tr>
</table>

</div>
</div>

<br/>

<div class="mboxfull">
<a href="javascript:showhide('Unit2')"><div class="mbox usermessage">Unit 2: Quantitative Data</div></a>

<div id="Unit2" style="display:none;">

<table class="tmain">
<tr>
<td><p>[Lesson 9: Inference for One Mean: Sigma Known (Hypothesis Test)](Lesson09.html) <a href="javascript:showhide('lesson09_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson09_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

- Conduct a Hypothesis Test for a single mean with σ known:
  + State the null and alternative hypothesis. 
  + Calculate the test-statistic and p-value of the hypothesis test.
  + Assess the statistical significance by comparing the p-value to the α-level.
  + Check the requirements for the hypothesis test.
  + Show the appropriate connections between the numerical and graphical summaries that support this hypothesis test. 
  + Draw a correct conclusion for the hypothesis test.
  + Interpret a Type I and II error.

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 10: Inference for One Mean: Sigma Known (Confidence Interval)](Lesson10.html) <a href="javascript:showhide('lesson10_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson10_Outcomes" style="display:none;">

By the end of this lesson, you should be able to:

* Calculate and interpret a confidence interval for a population mean given a confidence level.
* Explain how the margin of error changes with the sample size and the level of confidence. 
* Identify a point estimate and margin of error for the confidence interval.
* Show the appropriate connections between the numerical and graphical summaries that support this confidence interval. 
* Check the requirements of the confidence interval.
* Calculate a desired sample size given a level of confidence and margin of error. 
</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 11: Inference for One Mean: Sigma Unknown](Lesson11.html) <a href="javascript:showhide('lesson11_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson11_Outcomes" style="display:none;">

By the end of this lesson, you should be able to do the following with regards to confidence intervals and hypothesis testing.

**Regarding Confidence Intervals for a single mean with $\sigma$ unknown:**

* Calculate and interpret a confidence interval for a population mean given a confidence level.
* Identify a point estimate and margin of error for the confidence interval.
* Show the appropriate connections between the numerical and graphical summaries that support the confidence interval. 
* Check the requirements the confidence interval.
 
**Regarding Hypothesis Testing for a single mean with $\sigma$ unknown:**

* State the null and alternative hypothesis. 
* Calculate the test-statistic, degrees of freedom and p-value of the hypothesis test.
* Assess the statistical significance by comparing the p-value to the α-level.
* Check the requirements for the hypothesis test.
* Show the appropriate connections between the numerical and graphical summaries that support the hypothesis test. 
* Draw a correct conclusion for the hypothesis test.

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 12: Inference for Two Means: Paired Data](Lesson12.html) <a href="javascript:showhide('lesson12_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson12_Outcomes" style="display:none;">

By the end of this lesson, you should be able to do the following.

**Regarding Confidence Intervals for the mean of differences with dependent samples: **

- Calculate and interpret a confidence interval for the mean of differences given a confidence level.
- Identify a point estimate and margin of error for the confidence interval.
- Show the appropriate connections between the numerical and graphical summaries that support the   confidence interval.
- Check the requirements for the confidence interval.
  
**Regarding Hypothesis Testing for the mean of differences with dependent samples:**

  * State the null and alternative hypothesis. 
  * Calculate the test-statistic, degrees of freedom and p-value of the hypothesis test.
  * Assess the statistical significance by comparing the p-value to the α-level.
  * Check the requirements for the hypothesis test.
  * Show the appropriate connections between the numerical and graphical summaries that support the hypothesis test. 
  * Draw a correct conclusion for the hypothesis test.

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 13: Inference for Two Means: Independent Samples](Lesson13.html) <a href="javascript:showhide('lesson13_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson13_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 14: Inference for Several Means (ANOVA)](Lesson14.html) <a href="javascript:showhide('lesson14_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson14_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 15: Review for Exam 2](Lesson15.html) <a href="javascript:showhide('lesson15_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson15_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
</table>

</div>
</div>


<br/>

<div class="mboxfull">
<a href="javascript:showhide('Unit3')"><div class="mbox usermessage mw-customtoggle-Unit02">Unit 3: Categorical Data</div></a>

<div id="Unit3" style="display:none;">

<table class="tmain">
<tr>
<td><p>[Lesson 16: Describing Categorical Data: Proportions; Sampling Distribution of a Sample Proportion](Lesson16.html) <a href="javascript:showhide('lesson16_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson16_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 17: Inference for One Proportion](Lesson17.html) <a href="javascript:showhide('lesson17_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson17_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 18: Inference for Two Proportions](Lesson18.html) <a href="javascript:showhide('lesson18_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson18_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 19: Inference for Independence of Categorical Data](Lesson19.html) <a href="javascript:showhide('lesson19_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson19_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 20: Review for Exam 3](Lesson20.html) <a href="javascript:showhide('lesson20_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson20_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
</table>

</div>
</div>


<br/>

<div class="mboxfull">
<a href="javascript:showhide('Unit4')"><div class="mbox usermessage mw-customtoggle-Unit02">Unit 4: Bivariate Data</div></a>

<div id="Unit4" style="display:none;">

<table class="tmain">
<tr>
<td><p>[Lesson 21: Describing Bivariate Data: Scatterplots, Correlation, & Covariance](Lesson21.html) <a href="javascript:showhide('lesson21_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson21_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 22: Simple Linear Regression](Lesson22.html) <a href="javascript:showhide('lesson22_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson22_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr>
<td><p>[Lesson 23: Inference for Bivariate Data](Lesson23.html) <a href="javascript:showhide('lesson23_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson23_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
<tr class="alt">
<td><p>[Lesson 24: Review for Exam 4](Lesson24.html) <a href="javascript:showhide('lesson24_Outcomes')"><span style="font-size:8pt;float:right;">Show Outcomes</span></a>
<div id="lesson24_Outcomes" style="display:none;">

</div>
</p></td>
</tr>
</table>

</div>
</div>