---
title: "Lesson 8: Review for Exam 1"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: false
---
<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

Unit 1 introduced you to some foundational ideas in statistical theory. A firm grasp of these concepts will allow you to connect deeply with the statistical tools that you will be presented with in Units 2, 3, and 4. Use this page to review the Lesson Outcomes and Summaries in preparation for the Unit 1 Exam. If there are any lesson outcomes that you are not confident with, return to that lesson and review those outcomes in detail.


<br>

## Lesson 1 {.tabset .tabset-pills}

### Outcomes

1. Explain the course policies
2. Access course resources (course outline, lesson schedule, preparation activities, reading quizzes, homework assignments, assessments, etc.)
3. Communicate with the instructor and group members
4. Access statistical analysis software tools for class quizzes, assignments, and exams
5. Apply principles of the gospel of Jesus Christ in this class
6. Apply the three rules of probability for different probability scenarios

### Summary

<div class="RecapHeading">Lesson 01 Recap</div>
<div class="Summary">

- In this class you will use the online textbook that has been written for you by your statistics teachers. All of the assignments and quizzes will be based on the readings, so study it well.
- Most weeks will cover two lessons
- By doing the work, staying on schedule, and living the Honor Code you *will* succeed in this class!

- The three **rules of probability** are:
    1. A probability is a number between 0 and 1. 
$$0 \leq P(X) \leq 1$$
    2. If you list all the outcomes of a probability experiment (such as rolling a die) the probability that one of these outcomes will occur is 1. In other words, the sum of the probabilities in any probability is 1. 
$$\sum P(X) = 1$$
    3. The probability that an outcome will not occur is 1 minus the probability that it will occur. 
$$P(\text{not}~X) = 1 - P(X)$$

</div>
<br>


## Lesson 2 {.tabset .tabset-pills}

### Outcomes

1. Describe the five steps of the Statistical Process
2. Distinguish between an observational study and an experiment
3. Differentiate between a population and a sample
4. Describe each of the following sampling schemes:
    a. Simple random sampling
    b. Stratified sampling
    c. Systematic sampling
    d. Cluster sampling
    e. Convenience sampling
5. Explain the importance of using random sampling
6. Distinguish between a quantitative and a categorical variable

### Summary

<div class="RecapHeading">Lesson 02 Recap</div>
<div class="Summary">

- The **Statistical Process** has five steps: **D**esign the study, **C**ollect the data, **D**escribe the data, **M**ake inferences, **T**ake action.

- In a **designed experiment**, researchers control the conditions of the study. In an **observational study**, researchers don't control the conditions but only observe what happens.

- There are many sampling methods used to obtain a **sample** from a **population**:
  + A **simple random sample (SRS)** is a random selection taken from a population
  + A **systematic sample** is every ***k***<sup>th</sup> item in the population, beginning at a random starting point
  + A **cluster sample** is all items in one or more randomly selected clusters, or blocks
  + A **stratified sample** divides data into similar groups and an **SRS** is taken from each group
  + A **convenience sample** is one easily obtained in a less-than-systematic way and should be avoided whenever possible

- **Quantitative variables** represent things that are numeric in nature, such as the value of a car or the number of students in a classroom. **Categorical variables** represent non-numerical data that can only be considered as labels, such as colors or brands of shoes.

</div>
<br>


## Lesson 3 {.tabset .tabset-pills}

### Outcomes

1. Create a histogram from data
2. Interpret data presented in a histogram
3. Identify left-skewed, right-skewed, and symmetric distributions from histograms
4. Calculate the mean, median, and mode for quantitative data using software
5. Compare the centers of distributions using graphical and numerical summaries
6. Describe the effects that skewness or outliers have on the relationship between the mean and median
7. Distinguish between a parameter and a statistic 

### Summary

<div class="RecapHeading">Lesson 03 Recap</div>
<div class="Summary">


- A **histogram** allows us to visually interpret data. Histograms can be left-skewed, right-skewed, or symmetrical and bell-shaped.

- The **mean**, **median**, and **mode** are measures of the center of a distribution. The mean is the most common measure of center and is computed by adding up the observed data and dividing by the number of observations in the data set.

- A **parameter** is a true (but usually unknown) number that describes a population. A **statistic** is an estimate of a parameter obtained from a sample of the population. 

</div>
<br>


## Lesson 4 {.tabset .tabset-pills}

### Outcomes

1. Calculate a percentile from data
2. Interpret a percentile
3. Calculate the standard deviation from data
4. Interpret the standard deviation
5. Calculate the five-number summary using software
6. Interpret the five-number summary
7. Create a box plot using software
8. Determine the five-number summary visually from a box plot

### Summary

<div class="RecapHeading">Lesson 04 Recap</div>
<div class="Summary">

- The **standard deviation** is a number that describes how spread out the data are. A larger standard deviation means the data are more spread out than data with a smaller standard deviation.

- **Quartiles/percentiles**, **Five-Number Summaries**, and **Boxplots** are tools that help us understand data. The five-number summary of a data set contains the minimum value, the first quartile, the median, the third quartile, and the maximum value. A boxplot is a graphical representation of the five-number summary.

</div>
<br>



## Lesson 5 {.tabset .tabset-pills}

### Outcomes

1. State the properties of a normal distribution
2. Calculate the z-score for an individual observation, given the population mean and standard deviation
3. Interpret a z-score
4. Use the normal distribution to calculate probabilities for one observation
5. Approximate probabilities from a normal distribution using the 68-95-99.7 rule 
6. Calculate a percentile using the normal distribution

### Summary

<div class="RecapHeading">Lesson 05 Recap</div>
<div class="Summary">

- A **normal density curve** is symmetric and bell-shaped. The curve lies above the horizontal axis and the total area under the curve is equal to 1. 

- A **standard normal distribution** has a mean of 0 and a standard deviation of 1. The **68-95-99.7% rule** states that when data are normally distributed, approximately 68% of the data lie within $z=1$ standard deviation ($\sigma$) from the mean, approximately 95% of the data lie within $z=2$ standard deviations from the mean, and approximately 99.7% of the data lie within $z=3$ standard deviations from the mean. 

- A **z-score** tells us how many standard deviations away from the mean a given value is. It is calculated as: $\displaystyle{z = \frac{\text{value}-\text{mean}}{\text{standard deviation}} = \frac{x-\mu}{\sigma}}$

- The [**Normal Probability Applet**](https://byuimath.com/apps/normprob.html) allows us to use z-scores to calculate proportions, probabilities, and percentiles of being "above," "below," or "between" certain values.

- Percentiles can be calculated using the [**Normal Probability Applet**](https://byuimath.com/apps/normprob.html) by (1) shading the left tail only, (2) entering the desired percentile in the "Area" box, and (3) using the z-score from where the blue shaded region ends solve for $x$ in the equation $z=\frac{x-\mu}{\sigma}$.

<br/>
</div>
<br>



## Lesson 6 {.tabset .tabset-pills}

### Outcomes

1. Describe the concept of a sampling distribution of the sample mean
2. State the Central Limit Theorem 
3. Determine the mean of the sampling distribution of the sample mean for a given parent population
4. Determine the standard deviation of the sampling distribution of the sample mean for a given parent population
5. Determine the shape of the sampling distribution of the sample mean for a given parent population
6. State the Law of Large Numbers

### Summary

<div class="RecapHeading">Lesson 06 Recap</div>
<div class="Summary">

- The **distribution of sample means** is a distribution of all possible sample means ($\bar x$) for a particular sample size. 

- The **mean** of the distribution of sample means is the mean $\mu$ of the population: $\mu_{\bar{x}} = \mu$.

- The **standard deviation** of the distribution of sample means is the standard deviation $\sigma$ of the population divided by the square root of $n$: $\sigma_{\bar{x}} = \sigma/\sqrt{n}$.

- The distribution of sample means is **normal** in either of two situations: (1) when the data is normally distributed **or** (2) when, thanks to the **Central Limit Theorem (CLT)**, our sample size ($n$) is large. 

- The **Law of Large Numbers** states that as the sample size ($n$) gets larger, the sample mean ($\bar x$) will get closer to the population mean ($\mu$). This can be seen in the equation for $\sigma_{\bar{x}} = \sigma/\sqrt{n}$. Notice as $n$ increases, then $\sigma_\bar{x}$ will get smaller.
</div>
<br>



## Lesson 7 {.tabset .tabset-pills}

### Outcomes

1. Calculate the z-score for a sample mean, given the population mean and standard deviation
2. Use the normal distribution to calculate probabilities for a sample mean

### Summary

<div class="RecapHeading">Lesson 07 Recap</div>
<div class="Summary">

- When the distribution of sample means is normally distributed, we can use **z-scores** and the **probability applet** to calculate proportions and probabilities. A z-score is calculated as: $\displaystyle{z = \frac{\text{value}-\text{mean}}{\text{standard deviation}} = \frac{\bar x-\mu}{\sigma/\sqrt{n}}}$

- The **$P$-value** is the probability of getting a test statistic at least as extreme as the one you got, assuming $H_0$ is true. A $P$-value is calculated by finding the area under the normal distribution curve that is more extreme (farther away from the mean) than the z-score.
</div>
<br>
















## Navigation

<center>
| **Previous Reading** | **This Reading** | **Next Reading** |
| :------------------: | :--------------: | :--------------: |
| [Lesson 7: <br> Probability Calculations involving a Mean Response](Lesson07.html) | Lesson 08: <br> Review for Exam 1 | [Lesson 9: <br> Inference for One Mean: Sigma Known (Hypothesis Test)](Lesson09.html) |
</center>
