---
title: "Lesson 20"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_float: false
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

The following questions are intended to help you judge your preparation for this exam.  Carefully work through the problems.<br />  **These questions are repeated on the preparation quiz for this lesson.**

This is not designed to be a comprehensive review.  There may be items on the exam that are not covered in this review.  Similarly, there may be items in this review that are not tested on this exam.  You are strongly encouraged to review the readings, homework exercises, and other activities from Units 1-3 as you prepare for the exam. In particular, you should go over the [Review for Exam 1](Lesson08.html){target="_blank"} and the [Review for Exam 2](Lesson15.html){target="_blank"}. 

<!-- Use the <span style="font-variant:small-caps"> -->
<!-- [[Index]]</span> to review definitions of important terms. 
Index needs to be built-->

## Lesson Outcomes

<a href="javascript:showhide('oc')"><span style="font-size:8pt;">Click here to Show/Hide Outcomes for this Lesson</span></a>
<div id="oc" style="display:none;">
The expectation on the exam is the following outcomes. You should be able to do:

- All of the Outcomes from Lesson 08 (Unit 1) and Lesson 15 (Unit 2)
- Calculate and interpret a sample proportion.
- Summarize categorical data with a bar or pie chart. 
- Determine the mean, standard deviation and shape of a distribution of sample proportions.
- Calculate probabilities using a distribution of sample proportions.
- Confidence Intervals: 
  + Determining correct confidence interval for a given scenario. 
  + Calculate and interpret a confidence interval given a confidence level and a given parameter.
  + Identify a point estimate and margin of error for a given confidence interval.
  + Show the appropriate connections between the numerical and graphical summaries that support a confidence interval. 
  + Check the requirements for a confidence interval.
  + Calculate a confidence interval for a comparison of two proportions. 
- Conduct a Hypothesis Test for
  + A single mean with σ known.
  + A single mean with σ unknown.
  + Difference of two means with dependent samples.
  + The mean of differences with dependent samples.
  + Several means (ANOVA).
  + A single proportion.
  + A comparison of two proportions.
  + Test of Independence for categorical data.
  + A goodness of fitness test.
- Hypothesis Testing
  + Determining correct hypothesis test for a given scenario
  + State the null and alternative hypothesis for the chosen test. 
  + Calculate the test-statistic and p-value of the hypothesis test.
  + Assess the statistical significance by comparing the p-value to the α-level.
  + Check the requirements for the hypothesis test.
  + Show the appropriate connections between the numerical and graphical summaries that support a hypothesis test. 
  + Draw a correct conclusion for a hypothesis test.
</div>
<br>

## Lesson Summaries

<span class="Custom">Click on the link at right</span> for a review of the summaries from each lesson.
<a href="javascript:showhide('ls')"><span style="font-size:8pt;">Show/Hide Solution</span></a>
<div id="ls" style="display:none;">

**Here are the summaries for each lesson in Unit 3. Reviewing these key points from each lesson will help you in your preparation for the exam.**

<div class="RecapHeading">Lesson 16 Recap</div>
<div class="Summary">

- **Pie charts** are used when you want to represent the observations as part of a whole, where each slice (sector) of the pie chart represents a proportion or percentage of the whole.

- **Bar charts** present the same information as pie charts and are used when our data represent counts. A **Pareto chart** is a bar chart where the height of the bars is presented in descending order.

- $\hat p$ is a point estimator for true proportion $p$. $\displaystyle{\hat p = \frac{x}{n}}$

- The sampling distribution of $\hat p$ has a mean of $p$ and a standard deviation of $\displaystyle{\sqrt{\frac{p\cdot(1-p)}{n}}}$

- If $np \ge 10$ and $n(1-p) \ge 10$, you can conduct **probability calculations** using the Normal Probability Applet.
$$
\displaystyle {z = \frac{\textrm{value} - \textrm{mean}}{\textrm{standard deviation}}
= \frac{\hat p - p}{\sqrt{\frac{p \cdot (1-p)}{n}}}}
$$
<br>
</div>
<br>

<div class="RecapHeading">Lesson 17 Recap</div>
<div class="Summary">

- The **estimator** of $p$ is $\hat p$. $\displaystyle{ \hat p = \frac {x}{n}}$ and is used for both confidence intervals and hypothesis testing.

- You will use the Excel spreadsheet [CategoricalDataAnalysis.xlsx](./Data/CategoricalDataAnalysis_Hat.xlsx) to perform hypothesis testing and calculate confidence intervals for problems involving one proportion.

- The requirements for a confidence interval are $n \hat p \ge 10$ and $n(1-\hat p) \ge 10$. The requirements for hypothesis tests involving one proportion are $np\ge10$ and $n(1-p)\ge10$.

- We can determine the sample size we need to obtain a desired margin of error using the formula $\displaystyle{ n=\left(\frac{z^*}{m}\right)^2 p^*(1-p^*)}$ where $p^*$ is a **prior estimate** of $p$. If no prior estimate is available, the formula $\displaystyle{ \left(\frac{z^*}{2m}\right)^2}$ is used.
<br>
</div>
<br>

<div class="RecapHeading">Lesson 18 Recap</div>
<div class="Summary">

- When conducting hypothesis tests using two proportions, the null hypothesis is always $p_1=p_2$, indicating that there is no difference between the two proportions. The alternative hypothesis can be left-tailed ($<$), right-tailed($>$), or two-tailed($\ne$).

- For a hypothesis test and confidence interval of two proportions, we use the following symbols:
$$
\begin{array}{lcl}
\text{Sample proportion for group 1:} & \hat p_1 = \displaystyle{\frac{x_1}{n_1}} \\
\text{Sample proportion for group 2:} & \hat p_2 = \displaystyle{\frac{x_2}{n_2}}
\end{array}
$$

- For a hypothesis test only, we use the following symbols:

$$
\begin{array}{lcl}
\text{Overall sample proportion:} & \hat p = \displaystyle{\frac{x_1+x_2}{n_1+n_2}}
\end{array}
$$

- Whenever zero is contained in the confidence interval of the difference of the true proportions we conclude that there is no significant difference between the two proportions.

- You will use the Excel spreadsheet [CategoricalDataAnalysis.xlsx](./Data/CategoricalDataAnalysis_Hat.xlsx) to perform hypothesis testing and calculate confidence intervals for problems involving two proportions.
<br>
</div>
<br>

<div class="RecapHeading">Lesson 19 Recap</div>
<div class="Summary">

- The **$\chi^2$ hypothesis test** is a test of independence between two variables. These variables are either associated or they are not. Therefore, the null and alternative hypotheses are the same for every test:
$$
\begin{array}{1cl}
H_0: & \text{The (first variable) and the (second variable) are independent.} \\
H_a: & \text{The (first variable) and the (second variable) are not independent.}
\end{array}
$$

- The **degrees of freedom ($df$)** for a $\chi^2$ test of independence are calculated using the formula $df=(\text{number of rows}-1)(\text{number of columns}-1)$

- In our hypothesis testing for $\chi^2$ we never conclude that two variables are *dependent*. Instead, we say that two variables are *not independent*.
<br>
</div>
<br>
</div>
<br>

## Review Questions

**Questions 1 through 4: Decide which hypothesis test to use.** 

- Here is a list of hypothesis tests we have studied so far this semester. For each question identify the one hypothesis test that is most appropriate to the given situation. You may use a hypothesis test once, more than once, or not at all.

    a. One sample z-test
    b. One sample t-test
    c. Paired-samples t-test
    d. Independent sample t-test
    e. ANOVA
    f. Test of one proportion
    g. Test of two proportions
    h. Chi-Squared test of independence


1. In an article in the Journal of Small Business Management successful start-up businesses in the United States and Korea were compared. One set of data compared educational level (high school, undergraduate degree, master’s degree, doctoral degree) of people who managed successful start-up companies in the United States and Korea. You want to determine if education level differs between managers of successful start-up companies differs between these two countries. Which hypothesis test would be most appropriate for this analysis?


2. A human resources manager reported data from a recent involuntary Reduction in Force (RIF) at her company. You are an attorney and want to determine if age discrimination was a factor (it is illegal to discriminate against employees because of age). The company reported the number of employees in two groups: 40 years old or younger, and over 40 years old. They also reported the number of employees in each group who were terminated. You want to determine if both age groups were treated equally. Which hypothesis test would be most appropriate for this analysis?


3. A survey was conducted by a group of state lotteries. A random sample of 2406 adults completed the survey. A total of 248 were classified as “heavy” players. Of these, 152 were male. You want to determine if the proportion of male “heavy” lottery players is different than the proportion of males in the population, which is 48.5%. Which hypothesis test would be most appropriate for this analysis?


4. A student project compared the effectiveness of two different combination locks. One of the locks turned clockwise first and the other lock turned counterclockwise first. They asked 25 students to participate in the study. Each student was given the combination to each lock and asked to open the locks. The time it took them to open each lock was recorded. They want to determine if one of the locks is easier to open. Which hypothesis test would be most appropriate for this analysis?


**Questions 5 through 7: Decide which confidence interval to use.** 

- Here is a list of confidence intervals we have studied so far this semester. For each question identify the one confidence interval that is most appropriate for the given situation. You may use a confidence interval once, more than once, or not at all.

a. One sample z-confidence interval
b. One sample t-confidence interval
c. Paired-samples t-confidence interval
d. Independent sample t-confidence interval
e. Confidence interval for one proportion
f. Confidence interval for two proportions


5. A bank employs two appraisers. When approving borrowers for mortgages, it is imperative that the appraisers value the same types of properties consistently. To make sure this is the case, the bank evaluates six properties that both appraisers have recently valued.  Which confidence interval would be most appropriate for this study?


6. In a Wall Street Journal article on satisfaction with career paths, the percentage of psychology majors reporting they were “satisfied” or “very satisfied” with their career path was reported. The same data was also reported for accounting majors. You decide to construct a 95% confidence interval to see if the observed difference is significant. Which confidence interval would be most appropriate for this study?


7. DoubleStuf Oreo cookies are supposed to have twice the filling of regular Oreo cookies. You and some friends decide you want to know if that is a true assertion by the company who makes them. You take a sample of 55 DoubleStuf Oreo cookies and measure the amount of filling in each one. You need to construct a confidence interval to estimate the true mean filling amount of DoubleStuf Oreos in order to compare it to the filling amount found in regular Oreos. Which confidence interval would be most appropriate for this study?


8. Which one of the following best defines the notion of the significance level of a hypothesis test?

    a. The probability of rejecting $H_0$, whether it's true or not
    b. The probability of observing a sample statistic more extreme than the one actually obtained, assuming the null hypothesis is true
    c. The probability of the type I error
    d. The probability of the type II error


9. Which one of the following best defines the notion of the $P$-value of a hypothesis test?

    a. The probability of rejecting $H_0$, whether it's true or not
    b. The probability of observing a sample statistic more extreme than the one actually obtained, assuming the null hypothesis is true
    c. The probability of the type I error
    d. The probability of the type II error


10. Suppose you create a 95% confidence interval for a mean, and get (10, 20). You've been told to report this by saying something similar to, “We are 95% confident that the true mean is between 10 and 20." Exactly what does this mean?

    a. 95% of the data are between 10 and 20.
    b. 95% of the sample means are between 10 and 20.
    c. There is a 95% chance that the true mean is between 10 and 20.
    d. 95% of all 95% confidence intervals actually contain the true mean.


**Questions 11 through 13: Use the following information.** 

- You take a simple random sample of 100 adults from a town in the Western United States to determine the proportion of adults in the town who invest in the stock market.  Assume the unknown population proportion or percentage of people in town who invest in the stock market is $p=0.30$ (or 30%).

11. What is the mean of the distribution of the sample proportions?

    a. 30
    b. 70
    c. 0.70
    d. 0.30


12. What is the standard deviation of the distribution of the sample proportions?

    a. 0.004
    b. 0.046
    c. 0.458
    d. 4.583


13. What is the probability that your random sample of 100 adults will have a sample proportion less that 0.25?

    a. 0.138
    b. 0.124
    c. 0.876
    d. 0.862


**Questions 14 through 18: Use the following information.** 

- Accupril is meant to control hypertension.  In clinical trials of Accupril, 2142 subjects were divided into two groups. The 1563 subjects in the experimental group received Accupril. The 579 subjects in the control group received a placebo. Of the 1563 in the experimental group, 61 experienced dizziness as a side effect. Of the 579 subjects in the control group, 15 experienced dizziness as a side effect.

14. Let $p_1$ be the true proportion of people who experience dizziness while taking Accupril. Let $p_2$ be the true proportion of people who experience dizziness but do not take Accupril. Create a 95% confidence interval for $p_1 - p_2$.

    a. (0.006, 0.092)
    b. (-0.06, 0.92)
    c. (-0.004, 0.029)
    d. (-0.04, 0.29)
    e. (-0.003, 0.029)


- Perform a hypothesis test to see if the proportion of experimental group subjects who experience dizziness is different than the proportion of control group subjects who do. Let $p_1$ be the true proportion of people who experience dizziness while taking Accupril. Let $p_2$ be the true proportion of people who experience dizziness but do not take Accupril. Use a level of significance of $\alpha = 0.05$.


15. Which of the following pairs of hypotheses is the most appropriate for addressing this question?

    a. $H_0:~p_1=p_2$&nbsp;&nbsp;$H_a:~p_1<p_2$
    b. $H_0:~p_1=p_2$&nbsp;&nbsp;$H_a:~p_1\ne p_2$
    c. $H_0:~p_1=p_2$&nbsp;&nbsp;$H_a:~p_1>p_2$
    d. $H_0:~p_1<p_2$&nbsp;&nbsp;$H_a:~p_1=p_2$
    e. $H_0:~p_1 \ne p_2$&nbsp;&nbsp;$H_a:~p_1=p_2$
    f. $H_0:~p_1>p_2$&nbsp;&nbsp;$H_a:~p_1=p_2$


16. The value of your test statistic is:

    a. -1.361
    b. 0.897
    c. 1.923
    d. 1.458


17. The $P$-value of your test is:

    a. 0.045
    b. 0.014
    c. 0.072
    d. 0.145


18. Is there sufficient evidence to conclude that the true proportion of people who experience dizziness while taking Accupril is different than the true proportion of people who experience dizziness while not taking Accupril?

    a. Yes. I rejected $H_0$.
    b. Yes. I failed to reject $H_0$.
    c. Yes. I accepted $H_a$.
    d. No. I rejected $H_0$.
    e. No. I failed to reject $H_0$.
    f. No. I failed to accept $H_a$.


**Questions 19 through 22: Use the following information and table.**

- A survey was conducted of 1279 randomly selected adults aged 18 and older. They were asked “Are you a morning person or a night person?”

<br>
<br>

- The hypotheses for this study are:

$$
\begin{array}{rl}
H_0: & \text{Being a morning or evening person is independent of age} \\
H_a: & \text{Being a morning or evening person is not independent of age} \\
\end{array}
$$

<br>

- The results of the survey are given here:

  Preference       18-29   30-49   50-64   65+
  ---------------- ------- ------- ------- -----
  Morning Person   97      177     210     210
  Evening Person   131     167     200     190

  : Age
  
<br>

<!-- {| class="basic" -->
<!-- |+ Age -->
<!-- |- -->
<!-- !Preference!!18-29!!30-49!!50-64!!65+ -->
<!-- |- -->
<!-- !Morning Person -->
<!-- | align="center"| 97 || 177 || 210 || 210 -->
<!-- |- -->
<!-- !Evening Person -->
<!-- | align="center"| 131 || 167 || 200 || 190 -->
<!-- |} -->


- Conduct a test of independence. Use a level of significance of $\alpha=0.05$


19. Calculate the test statistic for this hypothesis test. Assume the requirements for the test are satisfied.

    a. 6.580
    b. 0.658
    c. 9.760
    d. 0.097


20. Calculate the $P$-value for this hypothesis test. Assume the requirements for the test are satisfied.

    a. 8.660
    b. 0.009
    c. 0.866
    d. 0.087


21. Should you reject $H_0$ or not? Explain.

    a. Yes. The $P$-value is less than 0.05.
    b. Yes. The $P$-value is greater than 0.05.
    c. Yes. Looking at the data we can see that the age is a factor in determining if you are a morning or a night person.
    d. No. The $P$-value is less than 0.05.
    e. No. The $P$-value is greater than 0.05.
    f. No. Young people are more likely to be a night person.


22. Do you have sufficient evidence to conclude that age makes a difference in whether a person is a morning or night person? Why or why not?

    a. Yes. The table makes this clear.
    b. Yes. I rejected $H_0$.
    c. Yes. I failed to reject $H_0$.
    d. No. The difference in the data in the table is entirely due to chance.
    e. No. I rejected $H_0$.
    f. No. I failed to reject $H_0$.
    
    
**Questions 23 and 29: Use the following information to answer each question.** 

- A recent book noted that only 20% of all investment managers outperform the Dow Jones Industrial Average over a five-year period.  A random sample of 200 investment managers that had graduated from one of the top ten business programs in the country were followed over a five-year period. Fifty of these outperformed the Dow Jones Industrial Average. Let $p$ be the true proportion of investment managers who graduated from one of the top ten business programs who outperformed the Dow Jones over a five-year period.

23. Based on the results of the sample, a 95% confidence interval for $p$ is:

    a. (1.95, 3.15)
    b. (0.0195, 0 .0315)
    c. (0.190, 0.310)
    d. (0.028, 0.031)
    e. (0.195, 0.315)
    f. We can assert that $p$ = 0.20 with 100% confidence, because only 20% of investment managers outperform the standard indexes.


24. Suppose you had been in charge of designing the study. What sample size would be needed to construct a margin of error of 2% with 95% confidence? Use the prior estimate of $p^* = 0.2$ for this estimate.
    
    a. $n=2401$
    b. $n=1537$
    c. $n=16$
    d. $n=1801$
    e. $n>30$


- Suppose you wish to see if there is evidence that graduates of one of the top ten business programs performs better than other investment managers. Conduct a hypothesis test. Use a level of significance of $\alpha=0.05$.


25. Which of the following pairs of hypotheses is the most appropriate for addressing this question?
    
    a. $H_0:~p=0.2$&nbsp;&nbsp;$H_a:~p<0.2$
    b. $H_0:~p=0.2$&nbsp;&nbsp;$H_a:~p\ne0.2$
    c. $H_0:~p=0.2$&nbsp;&nbsp;$H_a:~p>0.2$
    d. $H_0:~p<0.2$&nbsp;&nbsp;$H_a:~p=0.2$
    e. $H_0:~p\ne0.2$&nbsp;&nbsp;$H_a:~p=0.2$
    f. $H_0:~p>0.2$&nbsp;&nbsp;$H_a:~p=0.2$


26. How many measurements must you have in order to assure that $\hat p$ is normally distributed?

    a. $n\ge30$
    b. $n\ge5$
    c. $np\ge10$ and $n(1-p)\ge10$
    d. $np\ge5$ and $n(1-p)\ge5$


27. The value of your test statistic is:

    a. 1.768
    b. 0.039
    c. 1.923
    d. 0.077


28. The $P$-value of your test is:

    a. 1.768
    b. 0.039
    c. 1.923
    d. 0.077


29. Is there sufficient evidence to conclude that graduates from the top ten business programs perform better than other investment managers?

    a. Yes. I rejected $H_0$.
    b. Yes. I failed to reject $H_0$.
    c. Yes. I accepted $H_a$.
    d. No. I rejected $H_0$.
    e. No. I failed to reject $H_0$.
    f. No. I failed to accept $H_a$.
    

**Questions 30 and 33: Use the following information to answer each question.**

- Computer software is commonly used to translate text from one language to another. As part of his Ph.D. thesis, Philipp Koehn developed a phrase-based translation program called Pharaoh. The quality of the translation can vary. A good translation system should match a professional human translation. It is important to be able to quantify how good the translations produced by Pharaoh are. The IBM T. J. Watson Research Center developed methods to measure the quality of a translation from one language to another. One of these is the BiLingual Evaluation Understudy (BLEU). BLEU is a score ranging from 0 to 1 that indicates how well a computer translation matches a professional human translation of the same text. Higher scores indicate a better match. BLEU helps companies who develop translation software "to monitor the effect of daily changes to their systems in order to weed out bad ideas from good ideas."

- To compare Pharaoh's ability to translate with similar computer translation software, Koehn took a random sample of 100 blocks of Spanish text, each of which contained 300 sentences, and used Pharaoh to translate each of these to English. The BLEU score was calculated for each of the 100 blocks. He wants to use this data to see if it differs from the mean BLEU score of another leading translation software which has a population mean score of 0.295. Open the data file [BLEU-Scores.xlsx](./Data/BLEU-Scores.xlsx).

30. Assuming the requirements are satisfied, calculate a 95% confidence interval for the mean of the BLEU test scores.
<!--:a. 0.282, 0.292
b. 0.279, 0.301
c. 0.294, 0.304
d. 0.289, 0.297-->


31. Calculate the degrees of freedom and the test statistic for a test of $H_0: \mu = 0.295$ against $H_a: \mu \ne 0.295$. Assume the requirements are satisfied.
<!--:a. 99
b. -2.803-->


32. Calculate the `P`-value for a test of $H_0: \mu = 0.295$ against $H_a: \mu \ne 0.295$. Assume the requirements are satisfied.
<!--a. 0.005..0.007-->


33. Based on the results of this test, what would you conclude? Use a level of significance of $\alpha = 0.05$.

    a. We have sufficient evidence to say that the true mean is equal to 0.295.
    b. We have insufficient evidence to say that the true mean is equal to 0.295.
    c. We have insufficient evidence to say that the true mean is different than 0.295.
    d. We have sufficient evidence to say that the true mean is different than 0.295.


**Questions 34 and 38: Use the following information to answer each question.** 

- A study was done to test the notion that people are taller when they first wake up in the morning than in the evening right before they go to bed. To test this theory, the heights of children in a boarding school in India were measured. Values were recorded (in mm) for each child in the morning and again in the evening. You want to determine if the children are taller in the morning than in the evening. Open the file [AM/PM Heights.xlsx](./Data/AMPM=Heights.xlsx). <i>Define the differences as <u>AM Height</u> minus <u>PM Height</u></i>.

34. Give a 95% confidence interval for the true mean difference of heights.
<!--
a. 8.718..8.738
b. 10.465..10.445-->


- You also want to conduct a hypothesis test to determine if there is a decrease in heights from morning until evening.  Use a level of significance of $\alpha = 0.05$.

35. Give the test statistic for this test.
<!--
a. 22.436..22.456
b. -22.456..-22.436
-->


36. Give the degrees of freedom for this test.
<!--
  `df =`___________
a. 40-->


37. What is the P-value for this test?
<!--
  P-value`~~`___________
a. 0..0.001-->


38. Based on your results of this test, is there enough evidence to suggest that the children are taller in the morning than in the evening?

    a. Yes, because we rejected the null.
    b. Yes, because we failed to reject the null.
    c. No, because we rejected the null.
    d. No, because we failed to reject the null.

<br>

## Navigation

<center>
| **Previous Reading** | **This Reading** | **Next Reading** |
| :------------------: | :--------------: | :--------------: |
| [Lesson 19: <br> Inference for Independence of Categorical Data](Lesson19.html) | Lesson 20: <br> Review for Exam 3 | [Lesson 21: <br> Describing Bivariate Data: Scatterplots, Correlation, & Covariance)](Lesson21.html) |
</center>
